version: '3.8'

services:
  app:
    build: .
    container_name: risolva_container
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/risolva_catalogue
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: cedano123321
      JWT_SECRET_KEY: 237270aff7bec8705312cf6353fbd7d05284d2c6f9cf2c37de675ee57ae9d133
      JWT_EXPIRATION_TIME: 86400000
      SUPERADMIN_SECRET_KEY: '$2a$15$YQRYGBDGvxbmrdPaUXI8HuCyZN9Wez0UXp9UWC9Pso.irPJ8gVPcW'
    depends_on:
      - db
    restart: always

  db:
    container_name: postgresql_container
    ports:
      - 5432:5432
    image: postgres
    environment:
      POSTGRES_DB: risolva_catalogue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cedano123321
    restart: always
    volumes:
      - C:\Users\juan_\Desktop\Dev\02 - Risolva\01 - Backend - Catalogue\db:/var/lib/postgresql/data